---
- name: Update and Install Nginx
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      tags: update

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      tags: install

    - name: Always run this task
      debug:
        msg: This task will always run
      tags: always
