# Loop over a list of packages and install latest versions.
- name: my play with loops
  hosts: all
  tasks:
    - name: my task with loops
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - nginx
        - mariadb-server
        - curl
        - ssh