# Loop over a list of packages and use different states as per input.
- name: my play with loops
  hosts: web_servers
  tasks:

  - name: my task with loops
    apt:
      name: "{{ item.package_name }}"
      state: "{{ item.package_state }}"
    loop:
      - { package_name: "nginx", package_state: "latest"}
      - { package_name: "vim", package_state: "present"}
      - { package_name: "curl", package_state: "absent"}
      - { package_name: "sudo", package_state: "latest"}