---
- name: my play with conditions
  hosts: web_servers
  tasks:
    - name: my task1 with conditions
      apt:
        name: nginx
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: my task2 with conditions
      package:
        name: httpd
      when: ansible_facts['distribution'] == "CentOS"
